# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - coderobin-web

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_816ced2ec1c4428297d4356a6d1f5aad }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d1720150b7ac4ca3ba2d5bb18b93bcad }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
        file: ./docker/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'coderobin-web'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1a21102dcb4e4c3aaad02e2ad5d88e55 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_816ced2ec1c4428297d4356a6d1f5aad }}/coderobin.azurecr.io/web:${{ github.sha }}'
